fixtures:
  repositories:
    stdlib:  "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat:  "git://github.com/puppetlabs/puppetlabs-concat.git"
    staging: "https://github.com/nanliu/puppet-staging.git"
  symlinks:
    perforce: "#{source_dir}"
