HOSTS:
  centos-6.6-64-nocm:
    roles:
      - master
    platform: el-6-x86_64
    box : puppetlabs/centos-6.6-64-nocm
    box_url : puppetlabs/centos-6.6-64-nocm
    hypervisor : vagrant
CONFIG:
  type: foss
